CREATE TABLE IF NOT EXISTS payment_receipts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  receipt_number VARCHAR(80) NOT NULL UNIQUE,
  receipt_type ENUM('advance','balance','final') NOT NULL DEFAULT 'advance',
  sequence_no INT UNSIGNED NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  balance_due DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(40) NULL,
  payment_status_snapshot VARCHAR(60) NULL,
  collection_status_snapshot VARCHAR(60) NULL,
  source_event VARCHAR(80) NOT NULL,
  source_reference VARCHAR(190) NOT NULL,
  financial_transaction_id BIGINT UNSIGNED NULL,
  payment_id BIGINT UNSIGNED NULL,
  issued_by_admin_id BIGINT UNSIGNED NULL,
  receipt_html LONGTEXT NULL,
  metadata_json LONGTEXT NULL,
  issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_receipts_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_receipts_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL,
  CONSTRAINT fk_payment_receipts_admin FOREIGN KEY (issued_by_admin_id) REFERENCES admins(id) ON DELETE SET NULL,
  UNIQUE KEY uq_payment_receipts_source (order_id, source_event, source_reference),
  INDEX idx_payment_receipts_order (order_id),
  INDEX idx_payment_receipts_financial (financial_transaction_id),
  INDEX idx_payment_receipts_issued_at (issued_at)
) ENGINE=InnoDB;